import { brandIconTags, pageMetadataTags, PRIVATE_ROBOTS, SITE_ORIGIN, BRAND_ASSET_VERSION } from './page-metadata.js';

const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
export function pageHeaders(headers = new Headers()) {
  headers.set('Content-Type', 'text/html; charset=utf-8');
  headers.set('Cache-Control', 'no-store');
  headers.set('Referrer-Policy', 'no-referrer');
  headers.set('X-Robots-Tag', PRIVATE_ROBOTS);
  headers.set('X-Frame-Options', 'DENY');
  headers.set('X-Content-Type-Options', 'nosniff');
  headers.set('Cross-Origin-Opener-Policy', 'same-origin-allow-popups');
  headers.set('Content-Security-Policy', "default-src 'none'; script-src 'self' https://accounts.google.com/gsi/client; style-src 'self' 'unsafe-inline' https://accounts.google.com/gsi/style; connect-src 'self' https://accounts.google.com; frame-src https://accounts.google.com; img-src 'self' https://*.googleusercontent.com https://avatars.githubusercontent.com data:; font-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'");
  return headers;
}
export function connectPage({ clientId = '', handle = '', clientName = '', redirect = '', mode = 'connect', error = '', githubAuth = false, webSessions = false } = {}) {
  const consent = mode === 'authorize';
  const metadata = pageMetadataTags({
    noindex: true, type: 'website', title: `${consent ? 'Connect your account' : 'Connect your tools'} · Token Horizon`,
    description: 'Connect Token Horizon to your AI tools with MCP. Explore models and community rankings, and choose what your account shares.',
    url: `${SITE_ORIGIN}${consent ? '/oauth/authorize' : '/connect'}`,
    image: `${SITE_ORIGIN}/assets/og-connect.png?v=${BRAND_ASSET_VERSION}`,
    alt: 'Token Horizon MCP connector for your AI tools, models and published usage.'
  });
  const signIn = `<div id="auth-options" class="connector-auth-options"><div id="google-signin" aria-label="Sign in with Google"></div><button id="github-signin" class="github-signin" type="button" ${githubAuth ? '' : 'disabled'}><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 1a11 11 0 0 0-3.5 21.4c.55.1.75-.24.75-.53v-2.05c-3.06.67-3.7-1.3-3.7-1.3-.5-1.27-1.22-1.61-1.22-1.61-1-.69.07-.67.07-.67 1.1.08 1.68 1.12 1.68 1.12.98 1.68 2.56 1.2 3.19.92.1-.7.38-1.19.7-1.46-2.44-.28-5-1.22-5-5.43 0-1.2.43-2.18 1.13-2.96-.11-.28-.49-1.4.11-2.91 0 0 .92-.3 3.03 1.13a10.5 10.5 0 0 1 5.5 0c2.1-1.43 3.02-1.13 3.02-1.13.6 1.51.22 2.63.11 2.91.7.78 1.13 1.76 1.13 2.96 0 4.22-2.57 5.14-5.02 5.42.39.34.74 1.01.74 2.03v2.98c0 .29.2.64.76.53A11 11 0 0 0 12 1Z"/></svg>Continue with GitHub</button>${githubAuth ? '' : '<small class="auth-provider-note">GitHub sign-in is being configured.</small>'}</div><div id="identity" class="connector-identity" hidden></div>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${metadata}${brandIconTags()}<script src="/theme.js?v=20261001-4"></script><link rel="stylesheet" href="/connect.css?v=20261001"><link rel="stylesheet" href="/horizon-system.css?v=20261001-4"><link rel="stylesheet" href="/surfaces.css?v=20261001-4"><link rel="stylesheet" href="/theme.css?v=20261001-4"><script type="module" src="/connect.js?v=20261001-2"></script></head>
<body data-mode="${escape(mode)}" data-client-id="${escape(clientId)}" data-handle="${escape(handle)}" data-github-auth="${githubAuth ? 'true' : 'false'}" data-web-sessions="${webSessions ? 'true' : 'false'}"><header><a class="brand" href="/">Token Horizon<span class="brand-mark" aria-hidden="true">◉</span></a><span data-theme-control></span><nav aria-label="Main navigation"><a href="/models">Models</a><a href="/leaderboard">Community</a><a href="/docs/">Docs ↗</a></nav></header>
<main><section class="universe" aria-labelledby="intro"><div class="eyebrow"><span class="live-dot"></span> YOUR CONTEXT. IN ORBIT.</div><h1 id="intro">A little closer<br>to everything.</h1><p class="intro">Your models, your momentum,<br>and the tools you think with.</p><div class="hole-stage" aria-hidden="true"><div class="orbital-ring"></div><pre id="black-hole"></pre><span class="coordinate c-one">01 / CONNECT</span><span class="coordinate c-two">TOKEN HORIZON</span></div><div class="stage-footer"><span>Models · Community · Your account</span><button id="motion-toggle" type="button" aria-pressed="false">Pause animation</button></div></section>
<section class="connection" aria-labelledby="connection-title"><div class="connection-top"><span class="eyebrow">${consent ? 'AUTHORIZE A CONNECTION' : 'THE TOKEN HORIZON CONNECTOR'}</span><span class="step">${consent ? '01 — 02' : 'MCP / 1.0'}</span></div>
${error ? `<h2 id="connection-title">Connection interrupted.</h2><p class="lede">${escape(error)}</p><a class="primary" href="/connect">Back to connections</a>` : consent ? `
<div class="app-symbol" aria-hidden="true">↗</div><h2 id="connection-title">Bring your horizon<br>to ${escape(clientName || 'your tool')}.</h2><p class="lede">Choose what this application can access.<br>You can disconnect it at any time.</p>
<div class="destination"><span>Returning to</span><strong>${escape(redirect)}</strong><small>Application names are supplied by the client. Only connect an application you trust.${redirect.startsWith('localhost') || redirect.startsWith('127.0.0.1') ? ' This returns to an application on your device.' : ''}</small></div>
<form id="consent-form" method="post" action="/oauth/authorize"><input type="hidden" name="handle" value="${escape(handle)}"><input type="hidden" name="credential" id="credential"><div class="permissions"><div class="permission"><span class="check">✓</span><div><strong>Read your account</strong><p>Claimed profiles, published usage, model history, groups and report sharing settings.</p></div></div><input type="hidden" name="scope" value="account:read"><label class="permission optional"><input type="checkbox" name="scope" value="account:manage"><span><strong>Manage shared reports <i>Optional</i></strong><p>Allow this application to revoke your report links. No access to your Google or GitHub account, repositories or local files.</p></span></label><label class="permission optional"><input type="checkbox" name="scope" value="offline_access" checked><span><strong>Stay connected</strong><p>Refresh this connection for up to 30 days without signing in again.</p></span></label></div>${signIn}<div class="form-actions"><button class="secondary" type="submit" name="decision" value="deny" formnovalidate>Cancel</button><button class="primary" id="allow" type="submit" name="decision" value="allow" disabled>Connect account <span>↗</span></button></div></form>` : `
<div class="app-symbol" aria-hidden="true">↗</div><h2 id="connection-title">Good context.<br>Wherever you work.</h2><p class="lede">Explore models, compare prices and follow the community from your AI tools. Connect your account for your own usage and sharing controls.</p>
<div class="capability-grid"><span>↗ Model explorer</span><span>↗ Community rankings</span><span>↗ Prices &amp; plans</span><span>↗ Personal analytics</span></div><div class="endpoint"><div><span>REMOTE MCP ENDPOINT</span><button id="copy-endpoint" type="button">Copy</button></div><code>https://token-horizon.dev/mcp</code></div><p class="help">Add this URL as a remote MCP server in your client, then follow its sign-in prompt. Public data is also available without an account at <code>/mcp/public</code>.</p><a class="package-link" href="/downloads/token-horizon-plugin.zip">Download the Codex plugin <span>↓</span></a><details class="local-details"><summary>Using the Mac app, notch or widgets?</summary><p>The local MCP server reads the same engine as your desktop views, including usage, limits, sessions, system metrics and traces. Device-only data stays local.</p><a href="/docs/#mcp">Local setup instructions ↗</a></details>
<div class="manage-heading"><h3>Your connections</h3><span>You're in control</span></div><p class="help">Sign in to review access and disconnect applications.</p>${signIn}<div id="connections"></div>`}
<p id="status" role="status" aria-live="polite"></p><noscript><p>Enable JavaScript to sign in. Public MCP tools do not require sign-in.</p></noscript><div class="trust-note"><span aria-hidden="true">⌁</span><p>Only the data you publish. Your local prompts, provider credentials and device files stay on your machine.<a href="/docs/#usage">How your data is handled ↗</a></p></div></section></main><footer><span>ONE CLEAR VIEW.</span><a href="/">Back to Token Horizon ↗</a></footer></body></html>`;
}
